# Generated by Django 4.1.7 on 2023-02-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
